#Packages pour le projet

library(FactoMineR)
library(ade4)
library(questionr)
library(tidyverse)
library(explor)
library(cluster)
library(gtsummary)
library(magrittr)
library(TraMineR)
library(Hmisc)
library(GDAtools)
library(WeightedCluster)
library(descriptio)
library(ggplot2)
library(readxl)
library(stringr)
library(ggdendro)
library(devtools)
#library(JLutils) --> Pour bestcuttree
library(GGally)
library(purrr)
library(gridExtra)
library(xtable)
library(gt)
library(factoextra)
library(RColorBrewer)
library(sf)
library(tidygeocoder)
